### PR TITLE
 fixing possible cross-device rename causing EXDEV

### PR DESCRIPTION
**Pull request by gaodeng**

### CODE REVIEW

**Comment by bcomnes** [comment]
Good idea, @mafintosh any opinion?

**Comment by mafintosh** [comment]
This kinda defeats the purpose of the rename unless mv does some atomic magic behind the scene?

**Comment by bcomnes** [comment]
I doubt a copy would be atomic.

**Comment by bcomnes** [comment]
@gaodeng a variant of this module that supports the non-atomic operations for compatibility might be helpful.

**Pull request closed without merging**
